### PR TITLE
Support incomplete items of LSP server

### PR DESCRIPTION
**Pull request by matsui54**
Continuation of Shougo/ddc.vim#88.

### CODE REVIEW

**Comment by Shougo** [comment]
Please wait.  I should change source interface.
`gatherCandidates()` should rename to `gather()` like ddu.vim.

**Comment by matsui54** [comment]
OK.

**Comment by Shougo** [comment]
Hi.  I have updated source interface.

**Comment by matsui54** [comment]
Updated. It can be merged.

**Comment by Shougo** [comment]
Merged.

**Comment by matsui54** [comment]
Thank you!

**Pull request merged**
